apiVersion: v1
kind: ServiceAccount
metadata:
  name: backend-service-account
  namespace: default
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::XXXXXXXXXXXX:role/BackendRole
---
apiVersion: v1
kind: Pod
metadata:
  name: backend
  namespace: default
spec:
  serviceAccountName: backend-service-account
  containers:
    - name: aws-cli
      image: amazon/aws-cli
      command: ["/bin/bash", "-c", "--"]
      args: ["while true; do sleep 30; done;"]
  tolerations:
    - operator: Exists
      effect: NoSchedule
